repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ['--fix=lf']
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        files: ^src/.*\.(ts|tsx|js|css|html|json)$
        args: ['--config=./.prettierrc', '--ignore-path=./.prettierignore']
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v8.33.0'
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint
          - eslint-config-react-app
          - typescript
          - '@typescript-eslint/parser'
          - '@typescript-eslint/eslint-plugin'
          - eslint-config-prettier
          - eslint-plugin-jsx-a11y
          - eslint-plugin-prettier
          - eslint-plugin-react
          - eslint-plugin-react-hooks
        files: ^src/.*\.[jt]sx?$
        types: [file]
        args: ['--config=./.eslintrc.json', '--ignore-path=./.eslintignore']
