import React from 'react'
import './globals.css'
import 'react-toastify/dist/ReactToastify.css'
import 'yet-another-react-lightbox/styles.css'
import 'yet-another-react-lightbox/plugins/captions.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import ThemeProvider from '@/lib/Presentation/Provider/ThemeProvider'
import Header from '@/lib/Presentation/Component/Header'
import { ToastContainer } from 'react-toastify'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-100 dark:bg-black`}>
        <ThemeProvider>
          <div className="flex h-full max-h-screen min-h-screen w-full flex-col">
            <Header />
            {children}
          </div>
          <ToastContainer />
        </ThemeProvider>
      </body>
    </html>
  )
}
