name: Prebuild Check

on: 'push'

jobs:
  build-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - run: yarn
      - run: yarn type
      - run: yarn lint
